# Используем официальный Node.js образ
FROM node:22-slim

WORKDIR /app

COPY package*.json ./

RUN npm ci --prefer-offline --no-audit && npm i -g @nestjs/cli
RUN npm install --os=linux --libc=musl --cpu=x64 sharp

COPY . .

RUN npx prisma generate


EXPOSE 3000

CMD ["npx", "nodemon", "--legacy-watch", "--watch", "src", "--exec", "npm run start:dev"]

# docker-compose build --no-cache
# docker-compose up

# docker builder prune