# Используем официальный Node.js образ
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci
RUN npm install --save-dev nodemon
RUN npm i -g @nestjs/cli

COPY . .

RUN npx prisma generate


EXPOSE 3000

CMD ["npx", "nodemon", "--legacy-watch", "--watch", "src", "--exec", "npm run start:dev"]

# docker-compose build --no-cache
# docker-compose up

# docker builder prune